// @generated by protobuf-ts 2.8.2
// @generated from protobuf file "admin.proto" (package "admin", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { AdminGrpc } from "./admin";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetOrdersResponse } from "./admin";
import type { Empty } from "./google/protobuf/empty";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service admin.AdminGrpc
 */
export interface IAdminGrpcClient {
    /**
     * @generated from protobuf rpc: GetOrders(google.protobuf.Empty) returns (admin.GetOrdersResponse);
     */
    getOrders(input: Empty, options?: RpcOptions): UnaryCall<Empty, GetOrdersResponse>;
}
/**
 * @generated from protobuf service admin.AdminGrpc
 */
export class AdminGrpcClient implements IAdminGrpcClient, ServiceInfo {
    typeName = AdminGrpc.typeName;
    methods = AdminGrpc.methods;
    options = AdminGrpc.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetOrders(google.protobuf.Empty) returns (admin.GetOrdersResponse);
     */
    getOrders(input: Empty, options?: RpcOptions): UnaryCall<Empty, GetOrdersResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, GetOrdersResponse>("unary", this._transport, method, opt, input);
    }
}
